baseURL = 'localhost'
copyright = "© Lucinda Kindred"
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = 'en-us'
theme = 'nico-gallery'
timeZone = "America/Denver"
timeout = "120s"
title = 'Lucinda Kindred Art'

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]