baseURL = 'localhost'
copyright = "© Lucinda Kindred"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = 'en-us'
theme = 'gallery-dev'
timeZone = "America/Denver"
timeout = "120s"
title = 'Lucinda Kindred Art'

[taxonomies]
category = "categories"
series = "series"
tag = "tags"